// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiqBP95NVzZSXyQSXezAoMwsXNKNeLCw0',
    appId: '1:29303372161:web:de864d25ab1dbcb6ebd080',
    messagingSenderId: '29303372161',
    projectId: 'chate-app-55943',
    authDomain: 'chate-app-55943.firebaseapp.com',
    storageBucket: 'chate-app-55943.appspot.com',
    measurementId: 'G-0BLG8XR6CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBenqXlSEFxNvOh5U5Fn0Dq0bCtxBwqpDY',
    appId: '1:29303372161:android:535754a5219c01d6ebd080',
    messagingSenderId: '29303372161',
    projectId: 'chate-app-55943',
    storageBucket: 'chate-app-55943.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJcod7alpBYQPXApriAE8LfUjuG10YeR8',
    appId: '1:29303372161:ios:6f59ec9c12af44c8ebd080',
    messagingSenderId: '29303372161',
    projectId: 'chate-app-55943',
    storageBucket: 'chate-app-55943.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJcod7alpBYQPXApriAE8LfUjuG10YeR8',
    appId: '1:29303372161:ios:6f59ec9c12af44c8ebd080',
    messagingSenderId: '29303372161',
    projectId: 'chate-app-55943',
    storageBucket: 'chate-app-55943.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiqBP95NVzZSXyQSXezAoMwsXNKNeLCw0',
    appId: '1:29303372161:web:c09c815f6195bb25ebd080',
    messagingSenderId: '29303372161',
    projectId: 'chate-app-55943',
    authDomain: 'chate-app-55943.firebaseapp.com',
    storageBucket: 'chate-app-55943.appspot.com',
    measurementId: 'G-8VV0KRH87J',
  );
}
